name: ras2fim2d

channels:
  - conda-forge

dependencies:
  - python=3.8.12

  # Geospatial stack
  - gdal
  - rasterio
  - geopandas=0.12.1
  - fiona=1.8.22
  - pyproj
  - shapely
  - rioxarray=0.13.1

  # Scientific/data
  - h5py=3.7.0
  - netcdf4
  - h5netcdf
  - scipy=1.9.3
  - networkx=2.8.8

  # Other
  - matplotlib
  - tqdm
  - pywin32